services:
  # Servico Web: API Spring Boot e Frontend PWA (100% Gratuito - Plano Free, Sem Cartao)
  - type: web
    name: agritech-dondo-api
    env: docker
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: "jdbc:h2:file:/app/data/agritech;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDER=HIGH;DB_CLOSE_DELAY=-1"
      - key: SPRING_DATASOURCE_USERNAME
        value: "sa"
      - key: SPRING_DATASOURCE_PASSWORD
        value: "admin"
