services:
  # Servico Privado: Base de Dados MySQL
  - type: pserv
    name: agritech-db
    env: image
    image:
      url: mysql:8.0
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 1
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_DATABASE
        value: agritech_dondo_db

  # Servico Web: API Spring Boot e Frontend
  - type: web
    name: agritech-dondo-api
    env: docker
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://agritech-db:3306/agritech_dondo_db?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useUnicode=true
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        fromService:
          type: pserv
          name: agritech-db
          envVarKey: MYSQL_ROOT_PASSWORD
