# Configuracao do Servidor
server.port=${PORT:8080}
server.servlet.context-path=/

# FORÇAR ENCODING UTF-8 NO SPRING BOOT (Isto resolve os "??")
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

# Conexao com o Banco de Dados (MySQL local por padrao, ou H2 se configurado)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/agritech_dondo_db?useSSL=false&serverTimezone=Africa/Maputo&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useUnicode=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


jwt.secret=agritechDondoSecretKeySuperSeguraDistritoDeSofala2026MocambiqueCorredorBeiraChinamacondo
jwt.expiration=86400000


springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs


logging.level.com.agritech.dondo=INFO
logging.level.org.springframework.security=INFO